### ISSUE TITLE
Web UI not starting

### ISSUE THREAD

**Issue by achvaicer** [EthVentures/CryptoTracker#10]
Hello,

I'm already running CryptoTracker as seen on this terminal screenshot.
![screen shot 2017-09-24 at 13 52 03](https://user-images.githubusercontent.com/253457/30784669-cc553152-a12f-11e7-9752-d874ec0e349e.png)

But I can't enter on http://localhost:5601/ .
The site can't be reached.

This port is configurable?

Thanks for this amazing work.
I'd try to contribute as soon as possible.

**Comment by avelkoski** [comment]
Yes, the port is configurable. Sometimes you need to wait a couple of seconds for Kibana to start. Given the information provided, this doesn't appear to be an issue on our end.

**Comment by achvaicer** [comment]
Ok!
Great. Thanks!
