### ISSUE TITLE
Enable Code Modification

### ISSUE THREAD

**Issue by chaozdeus** [EthVentures/CryptoTracker#4]
How do I enable the new modification to the code?
I modified Poloniex.py 
self.products = {'USDT_ETH': 'eth.poloniex.ticker', 'USDT_BTC': 'btc.poloniex.ticker'}

tried restarting server and it didn't work.
thanks

**Comment by dconroy** [comment]
i hope to push some changes later tonight with an example for you.

**Comment by dconroy** [comment]
please check out the latest check in which adds support for GDAX btc, as well as new dashboards for BTC, ETH, and CryptoMarket overall

**Comment by chaozdeus** [comment]
So its only GDAX that's being queried for BTC data? or it also include the other servers? 
also, do I still need to modify the code like above to enable the parsing?

thanks!

**Comment by scrimpy** [comment]
this works for me:
       self.products = {'USDT_ETH': 'eth.poloniex.ticker',
                         'USDT_BTC': 'btc.poloniex.ticker'}

**Comment by chaozdeus** [comment]
If it helps.... this is the modification I did before

poloniex
	self.products = {'USDT_ETH': 'eth.poloniex.ticker', 'USDT_BTC': 'btc.poloniex.ticker'}
bitfinex
	self.products = {'ethusd':'eth.bitfinex.ticker', 'btcusd':'btc.bitfinex.ticker'}
gemini
	self.products = {'ETHUSD':'eth.gemini.ticker', 'BTCUSD':'btc.gemini.ticker'}
gdax
	self.products = {'ETH-USD': 'eth.gdax.ticker', 'btc-USD': 'btc.gdax.ticker'}
bittrex
	self.products = {'USDT-ETH':'eth.bittrex.ticker', 'USDT-BTC':'btc.bittrex.ticker'}
kraken
	self.products = {'XETHZUSD':'eth.kraken.ticker', 'XXBTZUSD':'btc.kraken.ticker'}

**Comment by scrimpy** [comment]
and is it working?

**Comment by scrimpy** [comment]
i've started to write scraper for okcoin and bithumb.

**Comment by chaozdeus** [comment]
yup 
![3040](https://user-images.githubusercontent.com/11864273/28965175-6427c62c-7942-11e7-9c84-1c4f4fb7bb4d.jpg)

**Comment by dconroy** [comment]
if you pull the latest commits we have built visualizations dedicated to  btc and eth, as well as a nice dashboard that can show both at the same time.

http://imgur.com/M9YfVR7

Thanks for the interest!

**Comment by dconroy** [comment]
@chaozdjinn @scrimpy thanks for your interest. based on this thread ive implemented BTC on all currently support exchanges, and with @avelkoski 's help we added new dashboards for kibana to help visualize these markets.  if you experience any issues with the lastest code over the next few days let me know, otherwise i'll mark this issue as closed.

thanks again for the contributions
