### ISSUE TITLE
Unable to fetch mapping

### ISSUE THREAD

**Issue by ginward** [EthVentures/CryptoTracker#5]
```
OS & Version:
MAC OSX 10.12.5

Python Version: 2.7.10

Docker version 17.06.0-ce, build 02c1d87
```

I installed the module with the command `docker-compose build && docker-compose up`. However, when I tried to access `http://localhost:5601/app/kibana`, it prompts me with the message `Unable to fetch mapping. Do you have indices matching the pattern?`. Is it because that the ElasticSearch is not running correctly? Or is it because the exchange data is not flowing in correctly?

**Comment by Bobur-kobilov** [comment]
Same issue with me as well. Did you find any solution for it?

**Comment by Bobur-kobilov** [comment]
I found the solution and it is written in the docs. You have to add these in the index management section:

eth.*.ticker
btc.*.ticker
*.*.ticker
