### ISSUE TITLE
Error Spike

### ISSUE THREAD

**Issue by chaozdeus** [EthVentures/CryptoTracker#9]
There was an error in one of the data returned by Kraken.. it was too large and now it skewed the graph....
![spike](https://user-images.githubusercontent.com/11864273/30138834-02bc6b5c-939d-11e7-8809-0db3b08cacba.png)
 any way of removing this?

thanks

**Comment by avelkoski** [comment]
There are a couple of ways that you can remove documents:

[Delete API](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docs-delete.html)
[Delete by Query](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docs-delete-by-query.html)

Let me know if you have any issues.

**Comment by avelkoski** [comment]
@chaozdjinn I'm going to close this out. Please reach out if you have any additional questions.
